import Aksioma from "../images/aksioma.png";
import Bogorsocialaction from "../images/bogorsocialaction.png";
import Coldestwinterkorea from "../images/coldestwinterkorea.png";
import Datascience101 from "../images/datascience101.png";
import Kersos from "../images/kersos.png";
import Kuliahgo from "../images/kuliahgo.png";
import Persiapankekorea from "../images/persiapankekorea.png";
import Solarsubmersible from "../images/solarsubmersible.png";
import Startup from "../images/startup.png";

export const BlogData = [
    {
        imagee: Kuliahgo,
        title: "Study Abroad to South Korea!",
        description:"As we know that South Korea is one of Asia’s most upcoming higher education destinations. I will define it as three kind of reason (study point of view, environment point of view, and economic point of view) why we should try South korea as our destination to study. ",
        content:{
            par1 : "As we know that South Korea is one of Asia’s most upcoming higher education destinations. I will define it as three kind of reason (study point of view, environment point of view, and economic point of view) why we should try South korea as our destination to study. ",
            par2 : "In the environment point of view, as an exchange student, you will meet people from all around the world. Korea is extraordinary for its mix of traditional and modern styles. And for me korean students are incredibly welcoming. In the education point of view, the information and communication technology of Korea is considered as one of the best in the world. Most universities in South Korea offer language lessons along with English language studies. There are a lot of universities with a wide range of courses. Lastly in the economic point of view, South Korea is Asia’s fourth-largest economy.It is one of the world’s leading financial centers. South Korea is providing best Scholarships in the world. Studying in South Korea will open up a wide range of employment opportunities. The cost of living in South Korea is affordable. In fact, 11.1 million foreign tourists visited South Korea and this country is one of the most favorable destination.",
            par3 : "The reason why I choose South Korea as my destination to study because I definitely love travelling. When I graduated from my bachelor program, I was asking to myself that “what should I do after completing my undergraduate program?” then some decision was come up, should I work first, or should I continue my study to pursuing my master degree and I just confused which way should I take, is it the right way or not. At the same time, I think that I can get it both (Pursuing my master degree and also work). The main concern is I want to pursue my master degree with my own money which means scholarship. Although it was so hard for me to find the scholarship, I should try my best. Then I get one opportunity to pursuing my master degree in South Korea, I get this Information from my lecture in my previous university (Universitas Indonesia). And I think that I should try to develop my skill and experience abroad. ",
            par4 : "There are lots of scholarship system in south korea but in this article I will try to explain 3 of the scholarship system, KGSP, LPDP, and also Excellent Researcher Scholarship. The Korean Government Scholarship Program is designed to provide higher education in Korea for international students with the aim of promoting international exchange in education, as well as mutual friendship amongst the participating countries. LPDP is committed to preparing future leaders and professionals and encouraging innovation for the realization of a prosperous, democratic, and just Indonesia. LPDP organizes a master / doctoral scholarship program for Indonesia's best sons and daughters, commercial / implementative research funding to encourage innovation, and rehabilitation of educational facilities damaged by natural disasters. Last one is the excellent researcher scholarship. This scholarship is provided by Campus and Lab. You will work as a Researcher and get an interesting work to do a project, writing SCI Paper, making a project etc. You will have a lot of experience here. Mostly, 75% of 1500 Indonesian students in Korea, use a researcher scholarship.",
            par5 : "Here is kind of Researcher Scholarship that I have got from my university: Living stipend: 700,000 – 1,000,000 KRW/month (Can negotiate with Professor depending on campus) Tuition fee, dormitory fee: paid by lab. Other benefits: Attending International Conference (ICTC.org, ICUFN.org, ICAIIC.org, ICOIN.org, etc). Attending Standard meeting (IEEE 802.15 standard meeting and ISO TC 204 standard meeting). Attending International Seminar and workshops.",
            par6 : "Documents that should be prepared : Application form, Recommendation Letter, Letter of Concern, All certificates, National Identity (You and Both your parents), Birth Certificate (You and Both your parents), Family Card, Graduation Certificate, Transcript, Passport, and Original Photo",
        },
    },
    {
        imagee: Bogorsocialaction,
        title: "Bogor Social Action (Sharing and Charity)",
        description:"Bogor social action was formed in 2014. It is a charity community for distributing aid and donations. Every year it holds social service activities, sharing session, charity, and break fasting together with orphaned foundations. .",
        content:{
            par1 : "Ramadan is the most sacred month of the year. It is the 9th month of Islamic calendar. Fasting is the fourth of the Five foundation of Islam during Ramadan. The foundation of how Muslims practice their religion is established by these foundations, or duties. According to the Islam Guide, the pillars of Islam are Shahada (trust sentences in the religion of Islam), Salat (prayer facing the direction of Mecca five times a day), Zakat (supporting the needy), Sawm (fast during Ramadan), and Hajj (pilgrimage to Mecca at least once during one's lifetime). Muslims are preparing to wake up early and eat a light meal, known as sahur, before dawn. Sahur is usually consumed in preparation for the fajr, or morning prayer, about half an hour before dawn. After the sun sets at the end of each day, muslims normally breaks his or her fast with water and dates, followed by prayers and then a meal called iftar.",
            par2 : "Muslims usually held iftar together every Ramadhan. This activity also one of the tools for us to have a great interaction and charity time. Through that kind of activity bogor social action was inspired to have a sharing and charity time in the iftar time.  Bogor social action was formed in 2014. Bogor Social Action is a charity community for distributing aid and donations. Every year it holds social service activities, sharing session, charity, and break fasting together with orphaned foundations. This activity is in collaboration with charity stakeholder and college students as agents of change. ",
            par3 : "So far we have done several charity to Panti Asuhan Putri Dan Balita Muhammadiyah Darushsholihat on 2014, Dormitory Orphans & Dhu'afa Sukasari on 2015, Panti asuhan Mizan Amanah Asrama Yatim dan Dhuafa Panduraya 2016, Yayasan Akbar Al-qi Foundation on 2017, Panti Yatim Indonesia (PYI Yatim dan Zakat) on 2018, Mizan Amanah Meranti Bogor on 2019. We are very open to those who want to make donations to be distributed to orphaned friends in need. We hope this community can be grow with the charity and giving tons of benefit to the lots of people.",
        },    },
    {
        imagee: Aksioma,
        title: "AKSIOMA 2016 (Student Social Action)",
        description:"AKSIOMA (Aksi Sosial Mahasiswa) or Student Social Action, is an activity that aims to introduce the world of community service, increase the value of interaction, togetherness and a sense of care in FTUI's new students.",
        content:{
            par1 : "Community service is one part of the Tri Dharma of Higher Education where the role of students is as agents of change. This role will relate directly to the community in their environment and as a tangible manifestation of student care and interaction with the community. Therefore, an activity called AKSIOMA was held for students who want to take their contribution in Faculty of Engineering, University of Indonesia.",
            par2 : "AKSIOMA (Aksi Sosial Mahasiswa) or Student Social Action, is an activity that aims to introduce the world of community service to new students, increase the value of interaction, togetherness and a sense of care in new students. It come up from the problems that exist in Faculty of Engineering, such as lack of interaction between students and non-student residents, the lack of a sense of kinship and care is embedded in students. Environmental problems such as garbage and reforestation will also be observed. AKSIOMA 2016 will make the FTUI environment better, especially for new students regarding community service.",
            par3 : "AKSIOMA's unique ideas this year (2016) are Care Stand, Amazing Race, and Tandur. The value of caring to the Master school children will also be instilled, as well as a sense of sharing with the holding of Care Stands and Charity Concerts. The purpose of this activity is to create new students from the FTUI class of 2016 in carrying out a form of community service, instilling and increasing a sense of social care for new students of the FTUI class of 2016, fostering a solid sense of one technique, especially for fellow new students of the FTUI class of 2016. Increases the interaction of new students with the Faculty of Engineering community, and provides benefits and togetherness to the community directly and concretely.",
            par4 : "In addition, the target of activities is also for the community outside of the faculty of engineering. Children from the Master school will be participate in enlivening the AKSIOMA 2016 closing series. The Master School is a free school under the auspices of the Yayasan Bina Insan Mandiri (YABIM), for poor children around Depok terminal. The MasTer School (acronym for MASjid TERminal) began to be built from the corner of the building where the worship place was. Some of its operations are supported by educational care institutions, community participation, the government, and independent business units. The teachers of the Master School are volunteers. The full excitement of this activity can be watched in the video below.",
            par5 : "Video : https://www.youtube.com/watch?v=B1-ulDidlYA",
        },    },
    {
        imagee: Solarsubmersible,
        title: "Clean Water Supply based on Renewable Energy in Sumber Jaya Village Banten",
        description:"Implementing a solar submersible pump at Sumber Jaya mosque. We are conducting our project execution with Ir. Chairul Hudaya, ST., M.Eng., PhD . The activity was carried out for 3 days. A total of 16 students contributed to this community service program.",
        content:{
            par1 : "The availability of water is very important since every aspect of life is linked. Access to water and sanitation may become a potential challenge, as water is the most critical survival factor. This problem is coupled with an increase in population growth in the region, so that water demand will increase with the growth of the national population of Indonesia, which increased by ± 1.3 percent annually in 2010-2017 [1]. Meanwhile, Indonesia has the potential for water sources of up to 3.9 trillion m3 every year and only 20% of which can only be maximized [2]. The national electrification ratio of Indonesia is 95.35 percent where the electrification growth ratio is in eastern Indonesia, NTT (59.85 percent) and Papua (61.42 percent) so that the realization and utilization of water is not optimal, especially in areas where the state-owned electricity company has not electrified due to the difficulty of accessing water for irrigation [3]. ",
            par2 : "The use of renewable energy as an energy source is one solution to the challenges of providing water access, especially in eastern Indonesia's inland areas. In this case, we have established a method that can be applied only to easily accessible places and can also be applied in remote areas. The design of the technology offered is based on a DC system that uses solar cell power (photovoltaic-PV) as an independent power supply to run a water pump, such as a submersible pump. This design is important for a pump to be configured to provide water access so that the distributed water can operate properly. In its application, solar powered pumps can be used in residential, livestock and even irrigation environments where their use includes water that is not reliant on the electrification of the state electricity company.",
            par3 : "Low electrification and limited provision of water access are constrained in inland areas or where infiltration is far from the object where it is irrigated. Various attempts have been made to solve this problem, one of the alternative solutions that we propose is a solar powered pump integrated system with the DC concept. We are investigating the optimal system for power linkage efficiency in solar powered pumps before and after the installation of solar panels.",
            par4 : "After the design process, we implemented our research results in Sumber Jaya Village, Banten. We are implementing a solar submersible pump at Sumber Jaya mosque, which is also under construction. We are conducting our project execution with Ir. Chairul Hudaya, ST., M.Eng., PhD . The activity was carried out for 3 days, from the planning, execution and testing of the submersible solar pump. A total of 16 students contributed to this community service program. We hope the solar submersible pump that we have implemented can be useful for irrigation sources for local residents.",
            par5 : "Reference : 1.	Statistik, B.P., Pertumbuhan Penduduk 2010-2017, S. Indonesia, Editor. 2017: Jakarta. 2.	Statistik, B.P., Proporsi Penduduk yang Memiliki Akses Terhadap Pelayanan Air Minum yang Layak dan Berkelanjutan 2015-2017, S. Indonesia, Editor. 2017: Jakarta. 3.	Indonesia, E.d.S.D.M.R., Rencana Usaha Penyediaan Tenaga Llistrik 2017-2026, ESDM, Editor. 2017: Indonesia.",
        },    },
        {
        imagee: Kersos,
        title: "KERSOS FTUI (Social Works of Faculty of Engineering Universitas Indonesia)",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla.",
        content:{
            par1 : "Every year, Kersos (Kerja Sosial) FTUI is committed to being able to contribute to the nation through the creation and growth of villages in remote areas of the country. Kersos 2016 was held on 5 to 11 June 2016. Kersos 2016 conducted in Panyaungan Village, Ciara District, Lebak Regency, Banten. In this village, there are RW 09 and RW 11. In fact, almost 99% of the houses in RW 11 do not have toilets to support their daily needs. So that the villagers have to walk far to the river to get water every day. The condition of the primary schools in this village is still very inadequate to support education for the children of Panyaungan Village.",
            par2 : "In Panyaungan village, I stayed at one of the residents' houses with four of my friends as students from the University of Indonesia. We stayed along that week because every afternoon we will have lots of implementation such as making toilets, free medical treatment, teaching, and playing with the children in the village. At that time, my group got the task of making the toilets, I took part in mixing the cement, and we also did voluntary work to clean the village environment with the residents. What a wonderful experience to serve the community through our real contributions as an engineers. In accordance with the tagline of the Kersos 2016, we must make real movements to build this country.",
            par3 : "#BergerakNyataMembangunBangsa",
        },    },
    {
        imagee: Persiapankekorea,
        title: "Study Abroad Preparation",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla.",
        content:{
            par1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
            par2 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
            par3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
            par4 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
            par5 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
        },    },
    {
        imagee: Coldestwinterkorea,
        title: "Coldest Winter in South Korea after last 30 years",
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla.",
        content:{
            par1 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
            par2 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
            par3 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
            par4 : "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus Lorem ipsum dolor sit amet, consectetur adipiscing elit. Iaculis et lectus tellus mi varius commodo nulla. Suspendisse accumsan, dui morbi vitae augue risus",
        },    
    },
]
