export const PubliData = [
    {
        year : "2022",
        papertitle : "An energy and leakage current monitoring system for abnormality detection in electrical appliances",
        confname : "SCIE Paper (Nature Journal)",
        pubdate : "2022-10-02",
    },
    {
        year : "2022",
        papertitle : "Multi-Level RNN-Based PM10 Air Quality Prediction for Industrial Internet of Things Applications in Cleanroom Environment",
        confname : "SCIE Paper (WCMC Journal)",
        pubdate : "2022-03-22",
    },
    {
        year : "2021",
        papertitle : "Forecasting PM2.5 Concentration Using a Single-Dense Layer BiLSTM Method",
        confname : "SCIE Paper (MDPI Electronics Journal)",
        pubdate : "2021-07-28",
    },
    {
        year : "2021",
        papertitle : "Battery Management using LSTM for Manhole Underground System",
        confname : "ICAIIC 2021",
        pubdate : "2021-04-29",
    },
    {
        year : "2021",
        papertitle : "Predictive Maintenance of Relative Humidity Using Random Forest Method",
        confname : "ICAIIC 2021",
        pubdate : "2021-04-29",
    },
    {
        year : "2021",
        papertitle : "Photovoltaic Power Generation Prediction based on Recurrent Neural Network",
        confname : "KICS WINTER 2021",
        pubdate : "2021-01-05",
    },
    {
        year : "2020",
        papertitle : "Wind Speed Interval Forecasting Under Uncertainty Quantification Pattern Based on Deep Learning Method",
        confname : "KAIC 2020",
        pubdate : "2020-12-20",
    },
    {
        year : "2020",
        papertitle : "Energy Management by Scheduling ESS with Active Demand Response in Low Voltage Grid",
        confname : "ICTC 2020",
        pubdate : "2020-11-10",
    },
    {
        year : "2020",
        papertitle : "Artificial Intelligence Forecasting for Photovoltaic Performance",
        confname : "KICS SUMMER 2020",
        pubdate : "2020-09-10",
    },
    {
        year : "2020",
        papertitle : "Automated Home Energy Management by Controlling ESS and Active Demand Response",
        confname : "KICS SUMMER 2020",
        pubdate : "2020-09-10",
    },
    {
        year : "2020",
        papertitle : "Smart Factory based on Internet of Things Platform",
        confname : "KICS SUMMER 2020",
        pubdate : "2020-09-10",
    },
    {
        year : "2020",
        papertitle : "Life Cycle Forecasting of Smart Factory Equipment Using Artificial Intellingence",
        confname : "KICS SUMMER 2020",
        pubdate : "2020-09-10",
    },
    {
        year : "2019",
        papertitle : "Analysis of Power Transformers Lifetime Using Health Index Transformer Method Base on Artificial Neural Network Modeling",
        confname : "ICEEI 2019",
        pubdate : "2020-02-10",
    },
]
